[package]
name = "splitdiff-rs"
version = "0.4.1"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust splitdiff implementation"

[dependencies]
clap = "2.32.0"
failure = "0.1.5"
lsdiff-rs = "0.1.2"
